Add shell script to generate certificates + update README.md to use openssl CLI
zapstar/two-way-ssl-c pull request #3
Opened 2024-01-10 14:47 UTC by agambier

Modifications added : 

- Rename app name to ssl-2way to prevent misunderstanding with the official openssl CLI.
- Add shell script to generate certificates & private keys.
- Update `README.md` so official openssl CLI can be used as the server or the client to validate the example.

2024-01-10 20:03 UTC, zapstar requested changes

2024-01-10 20:03 UTC, zapstar commented on README.md
> +3. You can generate the keys by looking at [this gist](https://gist.github.com/zapstar/4b51d7cfa74c7e709fcdaace19233443) or by using the included script `certs_gen.sh` (Uniy based OS).
typo: `Uniy` instead of `Unix`

2024-01-10 20:03 UTC, zapstar commented on certs_gen.sh
> +exit 0
Please add a newline in the end.

2024-01-10 20:04 UTC, zapstar commented
Thank you very much for the PR!

2024-01-11 08:58 UTC, agambier commented on README.md
> +3. You can generate the keys by looking at [this gist](https://gist.github.com/zapstar/4b51d7cfa74c7e709fcdaace19233443) or by using the included script `certs_gen.sh` (Uniy based OS).
done

2024-01-11 08:58 UTC, agambier commented on certs_gen.sh
> +exit 0
done

2024-01-11 09:49 UTC, zapstar approved these changes

2024-01-11 09:50 UTC, merged